services:
  app:
    build: .
    container_name: uv_app
    depends_on:
      - qdrant
    env_file:
      - .env.docker
    command: uv run uvicorn src.server.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"   # API HTTP
      - "6334:6334"   # gRPC
    volumes:
      - ./docker_volumes/qdrant:/qdrant/storage 
    restart: unless-stopped
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
