version: "3.9"

services:
  app:
    build: .
    container_name: uv_app
    depends_on:
      - qdrant
    env_file:
      - .env
    volumes:
      - .:/app
    command: uv run -m src.main
    ports:
      - "8000:8000"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"   # API HTTP
      - "6334:6334"   # gRPC
    volumes:
      - ./docker_volumes/qdrant:/qdrant/storage 
    restart: unless-stopped
